// <auto-generated />
using System;
using Assignment.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment.Migrations.AirlineDb
{
    [DbContext(typeof(AirlineDbContext))]
    [Migration("20250917131222_AlterNullableInAircraft")]
    partial class AlterNullableInAircraft
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment.Models.AirLineModel.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AL_Id")
                        .HasColumnType("int");

                    b.Property<string>("Assistant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Host01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Host02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maj_Pilot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AL_Id");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Aircraft_Route", b =>
                {
                    b.Property<int>("AC_ID")
                        .HasColumnType("int");

                    b.Property<int>("Route_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<int>("Num_Of_Pass")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("AC_ID", "Route_Id", "Departure");

                    b.ToTable("Aircraft_Routes");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cont_Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Airline_Phone", b =>
                {
                    b.Property<int>("AL_Id")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AL_Id", "Phone");

                    b.ToTable("airline_Phones");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Emp_Qualification", b =>
                {
                    b.Property<int>("Emp_Id")
                        .HasColumnType("int");

                    b.Property<string>("Qualifications")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Emp_Id", "Qualifications");

                    b.ToTable("Emp_Qualifications");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AL_Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BD_Day")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BD_Month")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BD_Year")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderEmp")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("GenderCode");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AL_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Distination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AL_Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AL_Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Aircraft", b =>
                {
                    b.HasOne("Assignment.Models.AirLineModel.Airline", "AL_Aircraft")
                        .WithMany("Aircrafts")
                        .HasForeignKey("AL_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AL_Aircraft");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Airline_Phone", b =>
                {
                    b.HasOne("Assignment.Models.AirLineModel.Airline", "AL_Phons")
                        .WithMany("Airline_Phones")
                        .HasForeignKey("AL_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AL_Phons");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Employee", b =>
                {
                    b.HasOne("Assignment.Models.AirLineModel.Airline", "EmpAirline")
                        .WithMany("Employees")
                        .HasForeignKey("AL_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpAirline");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Transaction", b =>
                {
                    b.HasOne("Assignment.Models.AirLineModel.Airline", "TransAirline")
                        .WithMany("Transactions")
                        .HasForeignKey("AL_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransAirline");
                });

            modelBuilder.Entity("Assignment.Models.AirLineModel.Airline", b =>
                {
                    b.Navigation("Aircrafts");

                    b.Navigation("Airline_Phones");

                    b.Navigation("Employees");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
